### ISSUE TITLE
Sorting by Date

### ISSUE THREAD

**Issue by apatton724** [tochoromero/aurelia-table#13]
Awesome Plugin.
The documentation doesn't give much detail on other objects to sort on or how to customize sort. 

How would you suggest I go about ordering a column by date?

`                    <thead>

                            <tr>

                                <th aut-sort="key.bind: nameLength">Customer</th>

                                <th aut-sort="key.bind: dateOrder">Date</th>

                                <th>Phone #</th>

                                <th>Address</th>

                               </tr>

                     `

I am wanting to add the code to this block of javascript:

`    dateOrder(row){

          ?

        }`

Thank you.

**Comment by tochoromero** [comment]
Thanks for checking out the plugin. As of right now you cannot do custom sort, but that is my next item to implement. I will have time to implement it today or tomorrow, so bear with me a little bit I will add that functionality very soon.

**Comment by apatton724** [comment]
That sound good to me! 

Let me know if I can contribute 👍

**Comment by tochoromero** [comment]
I have added the option to provide a custom sorting function. Please check the sorting section of the documentation.
https://tochoromero.github.io/aurelia-table/

**Comment by apatton724** [comment]
Worked like a charm 💯

**Comment by apatton724** [comment]
One sec,

I did try to sort on a more "complicated" date string, and the sorting function doesn't seem to like it. Nothing happens (no crash, or no sorting).

This is an example the date string coming from the server:
2002-10-04T03:05:07.65

which  converts to a date object like this:
Thu Oct 04 2002 23:05:07 GMT-0400 (Eastern Daylight Time)

After the call to:
 let date1 = new Date(a.creationTime);

in the dateSort function.


Any thoughts?

**Comment by tochoromero** [comment]
Hmm not sure here, have you debugged your method to see if it is doing the comparation correctly? I wonder if you need to specify the date format when creating the new Date object.

**Comment by apatton724** [comment]
We were using some dummy data generator that returned some unparseable stuff. 

Thanks again.
