### ISSUE TITLE
Unable to install via webpack

### ISSUE THREAD

**Issue by evenflow58** [tochoromero/aurelia-table#15]
The package is missing all the au-*.js files

**Comment by evenflow58** [comment]
I have a fix for this but I am unable to push my branch up to github to create a pull request. In the meantime you can add to the package.json file to force aurelia build to add in the required files.
`"aurelia": { 
    "build": { 
      "resources": [ 
        "aurelia-table/au-table", 
        "aurelia-table/au-table-pagination", 
        "aurelia-table/au-table-select", 
        "aurelia-table/au-table-sort" 
      ] 
    } 
  },`

**Comment by joshua1** [comment]
I have added this bit to my package.json , added 
``` .plugin('aurelia-table')
    .feature('resources');
```
 Still i get the error 
```cannot find module 'aurelia-table'``` I am using the webpack skeleton starter project
