### ISSUE TITLE
Feature: Publish to NPM 

### ISSUE THREAD

**Issue by rayalan** [tochoromero/aurelia-table#18]
This is a great aurelia extension with amazing documentation. Any chance that it can get published directly to npm so that we can more easily pin to specific versions and be aware of updates (e.g. `npm outdated`)?

**Comment by tochoromero** [comment]
Hey, thank you for the compliments. 
I did look into publishing to NPM, but there is already a plugin called aurelia-table. So I'm not sure how to proceed :(

I can use a different name I guess, but I wonder if that would confuse people. What do you suggest?

**Comment by tochoromero** [comment]
I have created a NPM package for the plugin. Unfortunately the aurelia-table name was already taken, so I had to settle with au-table instead.

I have updated the documentation to indicate this.

**Comment by rayalan** [comment]
Thanks; sounds like a great solution. (And a nice surprise when I got back from vacation.)
