### ISSUE TITLE
Issues with Usage over webpack skeleton

### ISSUE THREAD

**Issue by joshua1** [tochoromero/aurelia-table#20]
I get the error ```Cannot find module './aurelia-table'.``` using this with webpack skeleton. i think the aurelia-table being reffered here has to do with the resources config , as there isnt any aurelia-table in the source. please help me take a look. the docs only have instructions for the cli and JSPM

**Comment by tochoromero** [comment]
I will update the documentation today with Webpack instructions. I personally don't use webpack but I'm sure I can figure out how to set it up

**Comment by tochoromero** [comment]
I have tweaked the package.json to accommodate Webpack, and I also added instructions for Webpack installation
