### ISSUE TITLE
Can't apply sorting to dynamic columns

### ISSUE THREAD

**Issue by esnyder232** [tochoromero/aurelia-table#21]
Hey,

We're trying to make a table with dynamic headers.  The documentation states to sort by using "key: [column-name]".  If a key is "a string with the name of the column it will sort by" then by using the Aurelia convention you should be able to apply string interpolation like so:

 `<th repeat.for="col of headers" aut-sort="key: ${col}">`

This resulted in an error message saying that key was null.
Is there something we're doing wrong or do you think this is something that will be supported in the future?

Thanks,
Eric

**Comment by tochoromero** [comment]
Hello Eric.

This is a use case I have not considered before. I will see what can be done about it.

**Comment by tochoromero** [comment]
You were very close in your syntax. I just did some testing and this will work:
`<th repeat.for="col of headers" aut-sort="key.bind:col">`

Cheers

**Comment by esnyder232** [comment]
Yeah that worked!
Thanks alot man!

**Comment by tochoromero** [comment]
You are welcome :)
