### ISSUE TITLE
rowSelected($event) is called only when the row is selected

### ISSUE THREAD

**Issue by cosminonea** [tochoromero/aurelia-table#22]
https://github.com/tochoromero/aurelia-table/blob/master/src/au-table-select.js#L83

Is there any reason why rowSelected is not being called when an item is deselected?

**Comment by tochoromero** [comment]
No, there is really no reason. However I think that if I were to implement that functionality, it would have to be a new event, since triggering the same event, even with a flag or something, could break current applications using it. 

Any thoughts?

**Comment by cosminonea** [comment]
I was assuming that I need to keep track of the selected items. But the items in the view model get marked with an $isSelected which is perfect.

No need for a rowDeselected event.

**Comment by tochoromero** [comment]
Great, glad you figured it out :)
