### ISSUE TITLE
Bug when removing an item from array with element reference

### ISSUE THREAD

**Issue by doubleaa93** [tochoromero/aurelia-table#27]
Hello again, first of all thank so much for this plugin. While trying to apply some animation while removing rows I have found an issue. I've set up a very easy replicate example

[https://gist.run/?id=c4ddba38d9d583c3e9a848e0440c121e](https://gist.run/?id=c4ddba38d9d583c3e9a848e0440c121e)

If you look at this gist that I set up. I have 2 examples one with au-table and one without it.

In the first example if you click to remove item2. The backgroundcolor changes red and then after 1 secs it removes the item from the array, but row still red. If you then click to remove item4, instead of item4 getting highlighted item5 gets hightlited

If you try the same steps on the example without au-table everything works fine.

I can try to animate them by setting a property and binding to the class so if a row contains ${item.animate} it would add a class then with a timer remove the class an actually remove it from the array.

But using javascript animations  or JavaScript animation libraries like velocity.js on them might not work right now.

Let me know if you have a workaround on thisissue.

Thanks

**Comment by tochoromero** [comment]
Hello there.

I tweaked your code a little bit, it is working now.
https://gist.run/?id=446285dd83d8ba4ef44e7846b1dc91ec

I basically removed the element reference and instead used a CSS class to change the background. It is working as expected.
