### ISSUE TITLE
Sorting error when shifting between dynamically rendered tables.

### ISSUE THREAD

**Issue by TheSmedegaard** [tochoromero/aurelia-table#30]
My implementation uses the same view and view-model on different routes. The view renders different tables based on input from view-model. The tables consist of varying columns.

I  use the `aut-sort="key.bind:column"` in my table head.

Since there is no navigation between different views, an error occurs when I sort a table and shift to another. 
The error is `Uncaught TypeError: Cannot read property 'toString' of undefined`
I have traced the error to

```
doSort(toSort) {
    toSort.sort((a, b) => {
      if (typeof this.customSort === 'function') {
        return this.customSort(a, b, this.sortOrder);
      }

      let val1;
      let val2;

      if (typeof this.sortKey === 'function') {
        val1 = this.sortKey(a, this.sortOrder);
        val2 = this.sortKey(b, this.sortOrder);
      } else {
        val1 = this.getPropertyValue(a, this.sortKey);
        val2 = this.getPropertyValue(b, this.sortKey);
      }

      if (val1 === null) val1 = '';
      if (val2 === null) val2 = '';

      if (this.isNumeric(val1) && this.isNumeric(val2)) {
        return (val1 - val2) * this.sortOrder;
      }

      let str1 = val1.toString(); //<-- the error
      let str2 = val2.toString();

      return str1.localeCompare(str2) * this.sortOrder;
    });
  }

```
I don't think it is an error in this module. It's more my implementation that is a bit strange.
Is there a workaround to overcome this issue?

**Comment by tochoromero** [comment]
Could you please provide an example with the error?

**Comment by TheSmedegaard** [comment]
This is my view that can display multiple different tables "dynamically".
I also have a view-model you can see - but I don't think it is relevant. 
```
<template>
<div class="form-group">
    <input type="text" value.bind="filters[0].value" placeholder="Enter filter text" class="form-control"/>
</div>
  <table class="table table-striped" aurelia-table="data.bind: data; display-data.bind: $displayData; filters.bind: filters">
          <thead>
          <tr>
              <th repeat.for="column of columns" aut-sort="key.bind:column">${column} <i class="fa fa-sort"></i></th>
          </tr>
          </thead>
          <tbody>
          <tr repeat.for="row of $displayData" aut-select="row.bind: row; mode: single; selected-class:info">
              <td repeat.for="column of columns">${row[column]}</td>
          </tr>
          </tbody>
      </table>
</template>
```

---------------------------

**Here is one of my tables.**

![1](https://cloud.githubusercontent.com/assets/5764055/24039194/857c7892-0b04-11e7-8f08-98c03b5bc1ab.PNG)

**I click on "testName" to sort it... It works.**

![2](https://cloud.githubusercontent.com/assets/5764055/24039221/a9a2e9cc-0b04-11e7-9590-f8e911e1fe32.PNG)

**Then I shift to another route which has a different table.
But the data isn't loaded.**

![3](https://cloud.githubusercontent.com/assets/5764055/24039290/eeb3a902-0b04-11e7-88bf-7b3263562c01.PNG)

**I get this error in my console.**

![4](https://cloud.githubusercontent.com/assets/5764055/24039333/1058a896-0b05-11e7-90c4-3e08619bb330.PNG)

Does it make sense? I can elaborate more if you need it.

**Comment by TheSmedegaard** [comment]
Problem solved!
I used `activationStrategy: 'replace'` in the routing instead of `activationStrategy: 'invoke-lifecycle'`
This article may help anyone interested http://stackoverflow.com/questions/39999969/how-to-set-default-activationstrategy-in-aurelia

**Comment by tochoromero** [comment]
Nice, I'm glad you figured it out. And the tip is really good, I will keep it in mind.
