### ISSUE TITLE
Option to download result set

### ISSUE THREAD

**Issue by ryanhmaas** [tochoromero/aurelia-table#37]
First off, love the plugin. It's saved me tons of time.

I was wondering if there's a way (or plan to do so) to integrate a download button with the result set into a certain format, be it CSV, PDF, etc. If not, any suggestions?

**Comment by tochoromero** [comment]
Hello there, glad you are finding the plugin useful. 

Regarding a download option it wouldn't make a lot of sense to add that to the Aurelia table plugin, mainly because you already have access to both the raw items and the display items. 

What is that you are trying to achieve?
