### ISSUE TITLE
Error when used in webpack

### ISSUE THREAD

**Issue by raskolnikoov** [tochoromero/aurelia-table#38]
I can't seem to load the plugin when using webpack as my app-bundler.

These are my configs:

**webpack.config.js** 

```
module.exports = {
  entry: {
    'aurelia': ['aurelia-bootstrapper', 'au-table']
  }
}....
```

**main.js**
`aurelia.use.plugin(PLATFORM.moduleName('au-table'));`

**The error I get upon app-startup**

> Error: Unable to find module with ID: au-table/au-table
>     at WebpackLoader.<anonymous> (http://localhost:3000/app.js:11943:35)
>     at step (http://localhost:3000/app.js:11792:23)
>     at Object.next (http://localhost:3000/app.js:11773:53)
>     at http://localhost:3000/app.js:11767:71
>     at webpackJsonp.464.__awaiter (http://localhost:3000/app.js:11763:12)
>     at WebpackLoader.webpackJsonp.464.WebpackLoader._import (http://localhost:3000/app.js:11908:16)
>     at WebpackLoader.<anonymous> (http://localhost:3000/app.js:12008:44)
>     at step (http://localhost:3000/app.js:11792:23)
>     at Object.next (http://localhost:3000/app.js:11773:53)
>     at http://localhost:3000/app.js:11767:71

Using webpack@3.3.0 and latest aurelia version.

**Comment by raskolnikoov** [comment]
Nice! When will a new npm be available? :)

**Comment by tochoromero** [comment]
Now :)

**Comment by raskolnikoov** [comment]
Thanks! Works great! :)
