### ISSUE TITLE
Can't apply default sorting to dynamic columns

### ISSUE THREAD

**Issue by raffaele-clevermind** [tochoromero/aurelia-table#48]
Hi,

We're trying to make a table with dynamic columns; we managed to handle a dynamic sorting function, but we can't find a way to bind the "default" sorting.
Here is our current DOM:
```HTML
<th repeat.for="oColumn of columns" aut-sort="custom.bind: getSortingFunction( oColumn ) ;">
```
We tried to bind the default sorting like this:
```HTML
<th repeat.for="oColumn of columns" aut-sort="custom.bind: getSortingFunction( oColumn ) ; default: oColumn.order">
```

and like this:
```HTML
<th repeat.for="oColumn of columns" aut-sort="custom.bind: getSortingFunction( oColumn ) ;${ oColumn.order ? 'default:' + oColumn.order : ''}">
```
But neither work.
Is there a way to implement the desired functionality?

Thanks,
Raffaele

**Comment by dereke55** [comment]
I am having a similar issue:

To simplify, I was attempting to add dynamic sorting to the first column, but the string interpolation was throwing an error:
```
<template repeat.for="header of headers">
    <th if.bind="$first" aut-sort="key: ${header.value}">${header.name}</th>
    <th if.bind="!$first">${header.name}</th>
</template>
```

Being explicit works fine:
```
<template repeat.for="header of headers">
    <th if.bind="$first" aut-sort="key: dimension">${header.name}</th>
    <th if.bind="!$first">${header.name}</th>
</template>
```

**Comment by dereke55** [comment]
I don't completely understand it, but it looks like there was an issue with referencing of the component.  It seems to work if you add `ref="referenced"`

```
<template repeat.for="header of headers">
    <th if.bind="$first" ref="referenced" aut-sort="key: ${header.value}">${header.name}</th>
    <th if.bind="!$first">${header.name}</th>
</template>
```

@raffaele-clevermind - see if that works for your situation

**Comment by alexdrenea** [comment]
having the same issue, the `ref="referenced"` did not help in my case.

**Comment by raffaele-clevermind** [comment]
@alexdrenea @dereke55 i think i found a really simple solution. All i had to change in the cusom attributed was "the property"; so from :
```html
<th repeat.for="oColumn of columns" aut-sort="custom.bind: getSortingFunction( oColumn ) ; default: oColumn.order">
``` 

now it looks like 
```html
<th repeat.for="oColumn of columns" aut-sort="custom.bind: getSortingFunction( oColumn ) ; default.bind: oColumn.order">
``` 

I just nedded to specify the fact that instead of a string the default sort had to reference a variable
