### ISSUE TITLE
Access row counts after filtering is applied

### ISSUE THREAD

**Issue by MECLab-Michelle** [tochoromero/aurelia-table#55]
Hi, 

I'm working with aurelia-table filtering. I'd like to be able to have row counts in a panel header update as the filters are applied. I can't seem to see how to access the size of the data that is currently displayed. Can I access $displayQueueData to do this or is there some other way?

Cheers,

**Comment by csharpengineer** [comment]
In my table, I added a footer.

<tfoot>
<tr>
<th colspan="4">Displaying ${$displayData.length} of ${totalItems} ${totalItems == 1 ? 'item' : 'items'}</th>
</tr>
</tfoot>

**Comment by tochoromero** [comment]
As @csharpengineer mentioned `$displayData` is the currently displayed data
