### ISSUE TITLE
select does not work on striped tables

### ISSUE THREAD

**Issue by arnonuem** [tochoromero/aurelia-table#57]
I am using au-table 0.1.13

On striped tables only the white rows get the style which is assigned to selected-class.
On the gray rows the style has no effect.

**Comment by tochoromero** [comment]
The class is being applied, but it seems as if not because the colours for the row is the same both when it is selected and when it is not.
You will have to change your CSS to make them be different.

**Comment by arnonuem** [comment]
Please try to overwrite the color in CSS with "!important;" like "background-color: #eeffee !important;"
Maybe thats enough.
