### ISSUE TITLE
Provide sort direction in the sort key callback function

### ISSUE THREAD

**Issue by rmja** [tochoromero/aurelia-table#6]
I am having items in a table that should always be in the end, no matter the sort direction, so it would be convenient if the callback `nameLength` in:
```
<th aut-sort="key.bind: nameLength">Name</th>
```
had the sort direction as a second argument. In that way, one can write:
```
nameLength(row, direction) {
    if (row.alwaysLast) {
        return direction === 'asc' ? Infinity : -Infinity;
    }
    return row.name.length;
}
```

**Comment by tochoromero** [comment]
I have included the sortOrder as a second parameter. The values are 1 for ascending order and -1 for descending order. I will update the documentation accordingly.
