### ISSUE TITLE
Filter different column with different properties

### ISSUE THREAD

**Issue by patrek** [tochoromero/aurelia-table#7]
Nice plugin!

I know that you can use a property to filter for text in multiple columns (with filter-text and filter-keys).

Is there a way to do it so that different properties would finter in different columns?

I want to have multiple input field so I can filter in column A, then use a different input to filter in column C.

**Comment by tochoromero** [comment]
Unfortunately we don't have that capability yet. It is on my TODO list, but I haven't had a chance to implement it. I will update this issue once it is implemented.

**Comment by tochoromero** [comment]
I have committed a fix, you will have to get it from master for now though, because this are breaking changes I need to work in the documentation before I can create a release.
The change was basically to get rid of the fiterText and filterKeys properties and replace them with a filters property that takes in an array of objects like this:
    filters = [
      {value: '', keys: ['name', 'company']},
      {value:'', keys:['email']}
    ];

And then you bind each value to an input or select or whatever you want:
    <input value.bind="filters[0].value & throttle">

And of course you set the property in the table:
    <table aut-table="filters.bind: filters">

**Comment by tochoromero** [comment]
Sorry, It is not quite done, it breaks when you add multiple filters.

**Comment by tochoromero** [comment]
Ok, it seems to be working now, I will continue testing it. I would appreciate if you could give it a try.

**Comment by tochoromero** [comment]
@patrek I have done a release that includes the documentation to do multiple filters. I hope you find it useful.

**Comment by patrek** [comment]
Sorry, took me a while before I could test it.
Looks promising, the dist (from jspm install) then fails with the following error:
```Unhandled rejection ReferenceError: configureHtmlResourcePlugin is not defined
    at r.configure (http://localhost:8282/jspm_packages/github/tochoromero/aurelia-table@0.1.5/index.js:13:9)``

**Comment by tochoromero** [comment]
Weird, I will take a look after work. Thanks for bringing it up

**Comment by patrek** [comment]
Probably missing an import from html-resource-plugin, but you don't list it as a dependency in config.js.

**Comment by tochoromero** [comment]
@patrek I think I fixed the configuration, there is a new release you can try now, thanks.

**Comment by patrek** [comment]
Yes, it works as expected. Thanks!
